export enum DateScoreFilter {
    ENTIRE_RANGE = 5,
    LAST_YEAR,
    LAST_MONTH,
    LAST_WEEK,
    SAME_WEEK_DAY_AS_TODAY,
    SAME_MONTH_AS_TODAY,
    ODD_DAY,
    EVEN_DAY ,
    ODD_MONTH,
    EVEN_MONTH,
    SAME_YEAR_DAY_NUMBER,
    SAME_YEAR_QUARTER,
    SAME_MONTH_DAY_NUMBER,
}

