export enum ExpressionScore {
    SUM,
    AVERAGE,
    MIN_MAX_DIFFERENCE,
    MEDIAN,
    MEDIAN_ABSOLUTE_DEVIATION,
    PRODUCT,
    STANDARD_DEVIATION,
    MULTINOMINAL_COEFFICENTS,
    KULLBACK_LEIBLER_DIVERGENCE,
}
