export enum ExpressionScore {
    SUM,
    AVERAGE,
    MIN_MAX_DIFFERENCE,
    MEDIAN,
    MEDIAN_ABSOLUTE_DEVIATION,
    PRODUCT,
    STANDARD_DEVIATION,
    GREATEST_COMMON_DIVISOR,
    LEAST_COMMON_MULTIPLE,
}
